<form class="form contact"
action="<?php echo $this->getUrl('helloworld/index/post'); ?>"
id="makeoffer-form"
method="post"
data-hasrequired="<?php echo __('* Required Fields') ?>"
data-mage-init='{"validation":{}}'
autocomplete="on">  
<div id="makeoffer">    
	<fieldset class="fieldsetform">
<legend style="font-align:center;font-size:20px;color:blue"><center>Registration Form</center></legend>
		<div class="formfield required" >
			<label id="makeofferlable" class="label required" for="name"><span><?php  echo __('Name:') ?></span></label>
			<div class="control">
				<input name="custname" required id="name" placeholder="Enter Name here" title="<?php  echo __('Name:') ?>" tabindex="7" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('fname') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
			</div>
		</div>
<br></br>
		<div class="formfield required" >
			<label id="makeofferlable" class="label required" for="email"><span><?php  echo __('Email:') ?></span></label>
			<div class="control">
				<input name="custemail" id="email" placeholder="Enter Email here "title="<?php  echo __('Email') ?>" tabindex="3" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
			</div>
		</div>
<br></br>
		<div class="formfield required" >
			<label id="makeofferlable" class="label required" for="email"><span><?php  echo __('Gender:') ?></span></label><br></br>
			<div class="field choice">
				<input type="radio" class="radio" id="male" data-validate="{'validate-one-required-by-name':true}" name="gender" value="male">
				<label class="label" for="delivery-3-5">
					Male
				</label><br></br>
				<input type="radio" class="radio" id="female" data-validate="{'validate-one-required-by-name':true}" name="gender" value="female">
				<label class="label" for="delivery-3-6">
					Female
				</label>
			</div>
		</div>
<br></br>
		<div class="formfield required" >
			<label id="makeofferlable" class="label required" for="name"><span><?php  echo __('Country:') ?></span></label><br></br>
			<select id="country" name="country" class="validate-select required-entry">
				<option value="">Select Country</option>
				<option value="India">India</option>
				<option value="United Kingdom">United Kingdom</option>
				<option value="United States">United States</option>
			</select>
		</div>
<br></br>
		<div class="field comment  textarea">
			<label class="label" for="comment"><span><?php  echo __('Comments:') ?></span></label>
			<textarea name="custcomment" id="comment" title="<?php  echo __('Comments') ?>"  tabindex="9" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
		</div>
  
	</fieldset><br></br> 

	<div class="actions-toolbar">
		<div class="formbuttons">
			<button type="submit" title="<?php  echo __('Submit') ?>" tabindex="10"  class="action submit primary send">
				<span><?php  echo __('Submit') ?></span>
			</button>
		</div>
	</div>
</div>
</form>
<script type="text/javascript">
	require([
  'jquery',
  'mage/mage'
  ], function($,
    modal) {

   
    var dataForm = $('#makeoffer-form');
    dataForm.mage('validation', {});
    $("#makeoffer-form").on('submit',(function(e) {
      e.preventDefault();
      if(dataForm.validation('isValid')){

        var frurl = $('#makeoffer-form' ).attr( 'action' );
        $.ajax({
          url: frurl,
          data:  new FormData(this),
          processData: false,
          contentType: false,
          showLoader: true,
          type: 'POST',
          success: function(response) {
          	$(dataForm)[0].reset();
         }
       });
      }
    }));
  });
</script>

